server:
  port: 8091

spring:
  application:
    name: Spring-Cloud-consumer-eureka-feign-hystrix-resilience4j
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:123@192.168.1.82:8761/eureka/
  instance:
    prefer-ip-address: true  
    
feign:
  circuitbreaker:
    enabled: true
management:
  security:
    enabled: false    
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
hystrix:
  dashboard:
    proxy-stream-allow-list: "192.168.1.82"


resilience4j:
  circuitbreaker:
    configs:
      default:
        ringBufferSizeInClosedState: 5 # 熔断器关闭时的缓冲区大小
        ringBufferSizeInHalfOpenState: 2 # 熔断器半开时的缓冲区大小
        waitDurationInOpenState: 10000 # 熔断器从打开到半开需要的时间
        failureRateThreshold: 60 # 熔断器打开的失败阈值
        eventConsumerBufferSize: 10 # 事件缓冲区大小
        registerHealthIndicator: true # 健康监测
        automaticTransitionFromOpenToHalfOpenEnabled: false # 是否自动从打开到半开，不需要触发
        record-exceptions:
        recordExceptions: # 记录的异常
          - java.lang.Exception                
# 说明：请务必注意，从Spring Cloud Dalston开始，Feign默认是不开启Hystrix的。
# 因此，如使用Dalston请务必额外设置属性：feign.hystrix.enabled=true，否则断路器不会生效。
# 而，Spring Cloud Angel/Brixton/Camden中，Feign默认都是开启Hystrix的。无需设置该属性。    